// SPDX-License-Identifier: BlueOak-1.0.0
// SPDX-FileCopyrightText: 2023 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

= Windows HTA-based application installer

=== The story

https://github.com/sskras[@sskras] thought it would be nice to have a simple installation framework which:

  - would be text-based  +
    (could be fixed by hand / using notepad, with no rebuilding)

  - could run on as many retired NT versions as possible  +
    (going back to at least Win XP or even Win 2000)

  - would have no 3rd party dependencies  +
    (ones like Qt, Python, Perl, Lua, UI++)

So he ran some research and chose the Internet Explorer (IE)-based HTA
-- HTML Application technology introduced in 1999 along with IE5.

++++
<details><summary>
IE5 was supported on these OSes:
</summary>
++++

  - Windows 3.1x
  - Windows NT 3.51
  - Windows 95
  - Windows NT 4.0 SP3 or later
  - Windows 98
  - Mac OS X (up to v5.2.3)
  - Classic Mac OS (up to v5.1.7)
  - Solaris
  - HP-UX (up to 5.01 SP1)

By default it was bundled with:

  - Windows 98 Second Edition
  - Windows 2000
  - Windows ME

\... and so was the HTA support.

Via: https://en.wikipedia.org/wiki/HTML_Application  +
Via: https://en.wikipedia.org/wiki/Internet_Explorer_5
++++
</details>
++++

Which makes all three initial requirements satisfied.
